import SwiftUI

/// Confirms an agent switch. The handoff brief is generated by the core; the
/// sheet only collects the target agent and an optional prompt.
struct SwitchAgentSheet: View {
    let session: SessionViewDTO
    let agents: [AgentKind]
    let displayName: (AgentKind) -> String
    let symbol: (AgentKind) -> String
    let onSwitch: (AgentKind, String?) async -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var agent: AgentKind
    @State private var prompt = ""
    @State private var isSubmitting = false

    init(session: SessionViewDTO, agents: [AgentKind] = AgentKind.allCases, displayName: @escaping (AgentKind) -> String = { $0.title }, symbol: @escaping (AgentKind) -> String = { $0.symbol }, onSwitch: @escaping (AgentKind, String?) async -> Void) {
        self.session = session
        self.agents = agents.isEmpty ? AgentKind.allCases : agents
        self.displayName = displayName
        self.symbol = symbol
        self.onSwitch = onSwitch
        let current = session.currentAgent ?? .claude
        let all = agents.isEmpty ? AgentKind.allCases : agents
        _agent = State(initialValue: all.first { $0 != current } ?? current)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            PageTitle(
                title: "Wissel van agent",
                subtitle: agent == .terminal
                    ? "De terminal start een kale shell in dezelfde map, zonder Handoff Brief."
                    : "De nieuwe agent start in dezelfde worktree met een Handoff Brief en toegang tot het gedeelde geheugen."
            )

            Form {
                LabeledContent("Huidige agent", value: session.currentAgent?.title ?? "Onbekend")
                Picker("Nieuwe agent", selection: $agent) {
                    ForEach(agents) { candidate in
                        Label(displayName(candidate), systemImage: symbol(candidate)).tag(candidate)
                    }
                }
                if agent != .terminal {
                    TextField("Prompt (optioneel)", text: $prompt, axis: .vertical)
                        .lineLimit(2...5)
                }
            }
            .formStyle(.grouped)

            HStack {
                Spacer()
                Button("Annuleer") { dismiss() }
                    .buttonStyle(.omaSecondary)
                    .keyboardShortcut(.cancelAction)
                Button("Wissel agent") {
                    isSubmitting = true
                    Task {
                        await onSwitch(agent, agent == .terminal ? nil : prompt.nilIfBlank)
                        isSubmitting = false
                        dismiss()
                    }
                }
                .keyboardShortcut(.defaultAction)
                .buttonStyle(.omaPrimary)
                .disabled(isSubmitting || agent == session.currentAgent)
            }
        }
        .padding(24)
        .frame(width: 480)
        .background(OMAColor.canvas)
    }
}
