import SwiftUI

/// Confirms an agent switch. The handoff brief is generated by the core; the
/// sheet only collects the target agent and an optional prompt.
struct SwitchAgentSheet: View {
    let session: SessionViewDTO
    let onSwitch: (AgentKind, String?) async -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var agent: AgentKind
    @State private var prompt = ""
    @State private var isSubmitting = false

    init(session: SessionViewDTO, onSwitch: @escaping (AgentKind, String?) async -> Void) {
        self.session = session
        self.onSwitch = onSwitch
        let current = session.currentAgent ?? .claude
        _agent = State(initialValue: AgentKind.allCases.first { $0 != current } ?? current)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            VStack(alignment: .leading, spacing: 5) {
                Text("Wissel van agent")
                    .font(.title2.weight(.semibold))
                Text("De nieuwe agent start in dezelfde worktree met een Handoff Brief en toegang tot het gedeelde geheugen.")
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }

            Form {
                LabeledContent("Huidige agent", value: session.currentAgent?.title ?? "Onbekend")
                Picker("Nieuwe agent", selection: $agent) {
                    ForEach(AgentKind.allCases) { candidate in
                        Label(candidate.title, systemImage: candidate.symbol).tag(candidate)
                    }
                }
                TextField("Prompt (optioneel)", text: $prompt, axis: .vertical)
                    .lineLimit(2...5)
            }
            .formStyle(.grouped)

            HStack {
                Spacer()
                Button("Annuleer") { dismiss() }
                    .keyboardShortcut(.cancelAction)
                Button("Wissel agent") {
                    isSubmitting = true
                    Task {
                        await onSwitch(agent, prompt.nilIfBlank)
                        isSubmitting = false
                        dismiss()
                    }
                }
                .keyboardShortcut(.defaultAction)
                .buttonStyle(.borderedProminent)
                .tint(OMAColor.accent)
                .disabled(isSubmitting || agent == session.currentAgent)
            }
        }
        .padding(24)
        .frame(width: 480)
        .background(OMAColor.canvas)
    }
}
